### ISSUE TITLE
Confessors should be able to upload attachments

### ISSUE THREAD

**Issue by BastiDood** [BastiDood/spectro#11]
A huge win for Spectro would be the ability to upload arbitrary files/images/attachments to each confession. To improve security, the confessor must have the `ATTACH_FILES` permission for the command to be successful.

## Relevant Resources
* [Discord API: Create Message endpoint](https://discord.com/developers/docs/resources/message#create-message)
* [Discord API: Application Command Option type](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-type)
* [Discord API: `Attachment` object](https://discord.com/developers/docs/resources/message#attachment-object)
* [Discord API: Bitwise permission flags](https://discord.com/developers/docs/topics/permissions#permissions-bitwise-permission-flags)

**Comment by VeeIsForVanana** [comment]
I'm interested in taking on this issue. Thanks!

**Comment by VeeIsForVanana** [comment]
> Basically the confession flow is taking an Interaction and morphing it into a Message to be POST-ed to the creation endpoint, right now you're only allowing Interaction to have `content` option objects. So anyone who wants to implement attachments needs to create a way for the attachment objects to be taken along and converted with the content to the Message, along with the rest of the models and other infrastructure no?

Just leaving this here for future reference.
